---
namespace: giftpilz0
name: desktop
version: 1.0.0

description: Ansible collection for workstation related linux setups
readme: README.md
license:
  - GPL-3.0-only

authors:
  - Moritz Schmidt <schmidtmoritz404@gmail.com>

tags:
  - linux
  - pdf
  - libreoffice
  - python

dependencies:
  ansible.posix: ">=1.0.0"
  community.general: ">=1.0.0"

repository: https://github.com/giftpilz0/ansible-collection-desktop
